from enum import StrEnum


class ApplicationStatus(StrEnum):
    DISCOVERED = "DISCOVERED"
    ANALYZED = "ANALYZED"
    SKIPPED = "SKIPPED"
    READY_TO_APPLY = "READY_TO_APPLY"
    FORM_LOADING = "FORM_LOADING"
    FORM_ANALYZED = "FORM_ANALYZED"
    NEEDS_USER_INPUT = "NEEDS_USER_INPUT"
    READY_TO_ADVANCE = "READY_TO_ADVANCE"
    READY_FOR_REVIEW = "READY_FOR_REVIEW"
    APPROVED = "APPROVED"
    SUBMITTING = "SUBMITTING"
    SUBMISSION_UNCONFIRMED = "SUBMISSION_UNCONFIRMED"
    SUBMITTED = "SUBMITTED"
    FAILED = "FAILED"
    WAITING_FOR_USER = "WAITING_FOR_USER"
    REJECTED = "REJECTED"
    INTERVIEW = "INTERVIEW"
    OFFER = "OFFER"
    WITHDRAWN = "WITHDRAWN"
    ARCHIVED = "ARCHIVED"


class AnswerSource(StrEnum):
    CANDIDATE_PROFILE = "candidate_profile"
    ANSWER_BANK = "answer_bank"
    TRANSFORMATION = "deterministic_transformation"
    ATS_MAPPING = "ats_mapping"
    LLM_CLASSIFIED = "llm_classified"
    LLM_GENERATED = "llm_generated"
    USER_ENTERED = "user_entered"
    UNKNOWN = "unknown"


class Recommendation(StrEnum):
    STRONG_APPLY = "strong_apply"
    APPLY = "apply"
    MAYBE = "maybe"
    SKIP = "skip"


class EventType(StrEnum):
    JOB_IMPORTED = "JOB_IMPORTED"
    JOB_ANALYZED = "JOB_ANALYZED"
    APPLICATION_STARTED = "APPLICATION_STARTED"
    FIELD_DETECTED = "FIELD_DETECTED"
    FIELD_FILLED = "FIELD_FILLED"
    AI_ANSWER_GENERATED = "AI_ANSWER_GENERATED"
    USER_INPUT_REQUIRED = "USER_INPUT_REQUIRED"
    APPLICATION_REVIEWED = "APPLICATION_REVIEWED"
    APPLICATION_SUBMITTED = "APPLICATION_SUBMITTED"
    SUBMISSION_BLOCKED = "SUBMISSION_BLOCKED"
    SUBMISSION_UNCONFIRMED = "SUBMISSION_UNCONFIRMED"
    SUBMISSION_RETRY_AUTHORIZED = "SUBMISSION_RETRY_AUTHORIZED"
    MANUAL_SUBMISSION_ARMED = "MANUAL_SUBMISSION_ARMED"
    APPLICATION_ARCHIVED = "APPLICATION_ARCHIVED"
    APPLICATION_RESTARTED = "APPLICATION_RESTARTED"
    APPLICATION_FAILED = "APPLICATION_FAILED"
