import { FormEvent, useEffect, useState } from 'react'
import { ArrowLeft, ArrowRight, BriefcaseBusiness, FileUp, Link2, MapPin, Plus, Search, Sparkles } from 'lucide-react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { api, ApiError } from '../api'
import { EmptyState, ErrorMessage, Field, Loading, PageHeader, Score } from '../components'
import type { Application, Job, JobAnalysis, Resume } from '../types'

export function JobsPage(){
  const [jobs,setJobs]=useState<Job[]>();const[error,setError]=useState<unknown>();const[show,setShow]=useState(false);const[mode,setMode]=useState<'text'|'url'|'csv'>('text');const[search,setSearch]=useState('');const nav=useNavigate()
  const load=()=>api.get<Job[]>(`/jobs${search?`?search=${encodeURIComponent(search)}`:''}`).then(setJobs).catch(setError);useEffect(()=>{void load()},[search])
  const add=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setError(undefined);const form=e.currentTarget;const data=new FormData(form);try{let job:Job;if(mode==='url')job=await api.post('/jobs/from-url',{url:data.get('url')});else if(mode==='csv'){const result=await api.upload<{imported:number;duplicates:number;errors:string[]}>('/jobs/import-csv',data);alert(`Imported ${result.imported}; skipped ${result.duplicates} duplicates`);load();setShow(false);return}else job=await api.post('/jobs',{company:data.get('company'),title:data.get('title'),location:data.get('location')||null,description:data.get('description')||'',source_url:data.get('source_url')||null,application_url:data.get('application_url')||null,source:'manual_text'});nav(`/jobs/${job.id}`)}catch(err){const existingId=detailId(err,'existing_job_id');if(existingId){nav(`/jobs/${existingId}`);return}setError(err)}}
  if(!jobs&&!error)return <Loading/>
  return <><PageHeader eyebrow="Opportunity pipeline" title="Jobs" description="Import roles, compare them to factual profile data, and decide what deserves your time." action={<button className="button primary" onClick={()=>setShow(!show)}><Plus size={16}/> Add job</button>}/><ErrorMessage error={error}/>
    {show&&<section className="panel modal-panel"><div className="tabs"><button className={mode==='text'?'active':''} onClick={()=>setMode('text')}><BriefcaseBusiness size={15}/> Paste job</button><button className={mode==='url'?'active':''} onClick={()=>setMode('url')}><Link2 size={15}/> From URL</button><button className={mode==='csv'?'active':''} onClick={()=>setMode('csv')}><FileUp size={15}/> CSV import</button></div><form onSubmit={add} className="form-stack compact">{mode==='text'?<><div className="form-grid"><Field label="Company"><input name="company" required/></Field><Field label="Role title"><input name="title" required/></Field><Field label="Location"><input name="location"/></Field><Field label="Source URL"><input name="source_url" type="url"/></Field><Field label="Application URL"><input name="application_url" type="url"/></Field></div><Field label="Job description"><textarea name="description" rows={10} required/></Field></>:mode==='url'?<Field label="Public job URL" hint="Protected sites may require a visible browser and manual sign-in. CAPTCHAs are never bypassed."><input name="url" type="url" placeholder="https://company.example/jobs/123" required/></Field>:<Field label="CSV file" hint="Columns: company,title,url,location and optionally description"><input name="file" type="file" accept=".csv,text/csv" required/></Field>}<button className="button primary" type="submit">{mode==='url'?'Open & extract':mode==='csv'?'Import jobs':'Save job'}</button></form></section>}
    <div className="toolbar"><label className="search"><Search size={17}/><input placeholder="Search company or role" value={search} onChange={e=>setSearch(e.target.value)}/></label><span>{jobs?.length||0} opportunities</span></div>
    {jobs?.length?<div className="job-list">{jobs.map(job=><Link className="job-row panel" to={`/jobs/${job.id}`} key={job.id}><Score value={job.match_score}/><div className="job-main"><h2>{job.title}</h2><p>{job.company}{job.location&&<><span>·</span><MapPin size={14}/>{job.location}</>}</p><div className="tag-row"><span className="tag">{job.source.replace('_',' ')}</span>{job.recommendation&&<span className="tag strong">{job.recommendation.replace('_',' ')}</span>}{job.probable_duplicate_of&&<span className="tag warning">possible duplicate</span>}</div></div><ArrowRight size={19}/></Link>)}</div>:<EmptyState title="No opportunities imported">Paste a job description, load a public URL, or import a CSV to start building your pipeline.</EmptyState>}
  </>
}

export function JobDetailPage(){
  const{id}=useParams();const[job,setJob]=useState<Job>();const[analysis,setAnalysis]=useState<JobAnalysis>();const[resumes,setResumes]=useState<Resume[]>([]);const[resumeId,setResumeId]=useState('');const[error,setError]=useState<unknown>();const[busy,setBusy]=useState(false);const nav=useNavigate()
  useEffect(()=>{api.get<Job>(`/jobs/${id}`).then(setJob).catch(setError);api.get<Resume[]>('/resumes').then(data=>{setResumes(data);setResumeId(data.find(x=>x.is_default)?.id||data[0]?.id||'')})},[id])
  const analyze=async()=>{setBusy(true);setError(undefined);try{setAnalysis(await api.post<JobAnalysis>(`/jobs/${id}/analyze${resumeId?`?resume_id=${resumeId}`:''}`))}catch(e){setError(e)}finally{setBusy(false)}}
  const start=async()=>{setBusy(true);setError(undefined);try{const app=await api.post<Application>(`/jobs/${id}/applications`,{resume_id:resumeId||null});nav(`/applications/${app.id}/review`)}catch(e){const existingId=detailId(e,'existing_application_id');if(existingId){try{const existing=await api.get<Application>(`/applications/${existingId}`);const finished=['SUBMISSION_UNCONFIRMED','SUBMITTED','REJECTED','INTERVIEW','OFFER','WITHDRAWN'].includes(existing.status);nav(`/applications/${existingId}${finished?'':'/review'}`)}catch{nav(`/applications/${existingId}`)}return}setError(e)}finally{setBusy(false)}}
  if(!job&&!error)return <Loading/>
  return <><Link className="back-link" to="/jobs"><ArrowLeft size={16}/> Back to jobs</Link><ErrorMessage error={error}/>{job&&<><header className="detail-hero"><div><p className="eyebrow">{job.company}</p><h1>{job.title}</h1><p><MapPin size={16}/>{job.location||'Location not provided'}<span>·</span>{job.employment_type||'Employment type not provided'}</p></div><Score value={analysis?.overall_score??job.match_score} size="large"/></header>
    <div className="detail-actions panel"><div><label>Resume for this role</label><select value={resumeId} onChange={e=>setResumeId(e.target.value)}><option value="">No resume selected</option>{resumes.map(r=><option value={r.id} key={r.id}>{r.label}{r.is_default?' · default':''}</option>)}</select></div><button className="button secondary" onClick={analyze} disabled={busy}><Sparkles size={16}/>{busy?'Working…':'Analyze match'}</button><button className="button primary" onClick={start} disabled={busy}>Start application <ArrowRight size={16}/></button></div>
    {analysis&&<section className="analysis-grid"><article className="panel analysis-summary"><p className="eyebrow">Recommendation</p><h2>{analysis.recommendation.replace('_',' ')}</h2><p>{analysis.summary}</p><small>{analysis.ai_used?'Validated AI analysis':'Deterministic local analysis'} · {new Date(analysis.created_at).toLocaleString()}</small></article><article className="panel score-breakdown">{[['Skills',analysis.skill_match_score],['Experience',analysis.experience_match_score],['Education',analysis.education_match_score],['Location',analysis.location_match_score]].map(([name,value])=><div key={String(name)}><span>{name}</span><div className="bar"><i style={{width:`${value}%`}}/></div><strong>{value}</strong></div>)}</article><AnalysisList title="Strengths" items={analysis.strengths} tone="positive"/><AnalysisList title="Potential gaps" items={analysis.concerns} tone="warning"/><AnalysisList title="Must-have requirements" items={analysis.must_have_requirements} tone="neutral"/><AnalysisList title="Unmet must-haves" items={analysis.unmet_must_have_requirements} tone="negative"/></section>}
    <section className="panel description-panel"><div className="panel-heading"><h2>Job description</h2>{job.source_url&&<a href={job.source_url} target="_blank" rel="noreferrer">Open source <ArrowRight size={14}/></a>}</div><div className="job-description">{job.description||'No description was provided.'}</div></section></>}</>
}
function AnalysisList({title,items,tone}:{title:string;items:string[];tone:string}){return <article className={`panel analysis-list ${tone}`}><h3>{title}</h3>{items.length?<ul>{items.map((x,i)=><li key={i}>{x}</li>)}</ul>:<p>None identified.</p>}</article>}

function detailId(error: unknown, key: string): string | undefined {
  if (!(error instanceof ApiError) || !error.detail || typeof error.detail !== 'object') return undefined
  const value = (error.detail as Record<string, unknown>)[key]
  return typeof value === 'string' ? value : undefined
}
